version: '3.8'

services:
  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure

  mariadb:
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    secrets:
      - db_root_password
      - db_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    secrets:
      - credentials
      - db_password
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    expose:
      - "9000"

  redis:
    container_name: redis
    networks:
      - inception
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - "6379"

  adminer:
    container_name: adminer
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "9090:9090"

  ftp-server:
    container_name: ftp-server
    networks:
      - inception
    build:
      context: ./requirements/bonus/ftp-server
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    volumes:
      - wordpress:/home/wordpress:rw
    env_file:
      - .env
    secrets:
      - ftp_password

  cadvisor:
    container_name: cadvisor
    networks:
      - inception
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  website:
    container_name: website
    networks:
      - inception
    build:
      context: ./requirements/bonus/website
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "60:60"

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt
  ftp_password:
    file: ../secrets/ftp_password.txt

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/yel-hadr/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/yel-hadr/data/wordpress

networks:
  inception:
    driver: bridge
