version: '3.8'


services:
  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure

  mariadb:
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    expose:
      - "9000"

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/yel-hadr/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: /home/yel-hadr/wordpress

networks:
  inception:
    driver: bridge
